stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/loan_data.csv
      - params.yaml
    params:
      - data
      - model.test_size
      - model.random_state
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/feature_names.json

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - params.yaml
    params:
      - model
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - params.yaml
    params:
      - evaluate
    metrics:
      - reports/metrics.json:
          cache: false